version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    container_name: db-mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
  mongo-express:
    image: mongo-express
    restart: always
    container_name: db-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
#  mysql:
#   image: mysql
#   restart: always
#   container_name: db-mysql
#   ports:
#    - 3306:3306
#   environment:
#     MYSQL_DATABASE: testdb
#     MYSQL_ROOT_PASSWORD: 1234
#     MYSQL_USER: testuser
#     MYSQL_PASSWORD: testpassword
#   volumes:
#    - ./dump:/docker-entrypoint-initdb.d
#  app:
#    build:
#      context: .
#    ports:
#      - 5555:5555
#    container_name: demo
#    environment: 
#      WAIT_HOSTS: 
#        - mongo:27017
#        - mysql:3306
#    depends_on: 
#      - mongo
#      - mysql